[package]
name = "neewerctl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.9.0"
crossfire = "0.1.7"
tokio = {version = "1.15.0", features = ["macros"]}
tokio-stream = "0.1.8"
